branches:
  only:
    - master

language: node_js

sudo: false

node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - git config --global user.name "kimyLee"
  - git config --global user.email "1095643875@qq.com"
  - git clone --branch gh-pages https://github.com/vue-blog.git dist

script:
  - npm run build

after_success:
  - cd dist
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

env:
  global:
    - GH_REF: github.com/kimyLee/vue-blog.git
